pipeline:
  agent:
    any:
  stages:
    - stage: "Checkout"
      steps:
        - git "https://github.com/Nagashreer6515/OPENcart.git"
    - stage: "Build"
      steps: 
        - echo "Building the Code.........."
        - bat "mvn clean"
    - stage: 'Test'
      steps:
        - echo "Testing the Code.........."
        - bat "mvn test"
    - stage: 'Compile'
      steps:
        - echo "Compiling the Project.........."
        - bat "mvn compile"
    - stage: 'Deploy' 
      steps:
        - echo "Deploying the Project.........."
